---
- name: Install httpd package on all hosts 
  hosts: all
  become: true
  tasks:
  - name: Install httpd package
    yum:
      name: httpd
      state: installed
    notify: start apache #tells a task to trigger a specific background operations task (called a "handler") named start apache

  handlers:
  - name: start apache
    service:
      name: httpd
      state: started
